### ISSUE TITLE
Invitación de Discord rota

### ISSUE THREAD

**Issue by cfuendev** [faztcommunity/fazt-community-docs#4]
Todos los links que llevan al discord apuntan a una invitación expirada. Estos links están en las líneas [34](https://github.com/faztcommunity/fazt-community-docs/blob/56e8ad877021980f44ec57905bd88cbe959ca7ba/docs/README.md?plain=1#L34) y [72](https://github.com/faztcommunity/fazt-community-docs/blob/56e8ad877021980f44ec57905bd88cbe959ca7ba/docs/README.md?plain=1#L72).

Lo que sale cuando hago click en el link:
<img width="400" src="https://user-images.githubusercontent.com/65634520/172297039-0f4b1a28-dc6b-4799-a6af-7368f1999ff5.png">

**Comment by rdev32** [comment]
gracias por notificarnos, 
estamos en un proceso de renovar los docs de la comunidad lo cual va a reformular algunas reglas
ademas de agregar guias para los usuarios y futuros moderadores/admins

esto va a tomar tiempo asi que por ahora solo modificare los links
pero en las proximas semanas veras actualizaciones
